In [2]:
import numpy as np
import os
import PIL
import PIL.Image
import tensorflow as tf
# import tensorflow_datasets as tfds

In [18]:
batch_size = 32
img_height = 256
img_width = 256
data_dir = 'bottle/test'

In [19]:
train_ds = tf.keras.utils.image_dataset_from_directory(
  data_dir,
  validation_split=0.1,
  subset="training",
  seed=123,
  image_size=(img_height, img_width),
  batch_size=batch_size)

Found 83 files belonging to 5 classes.
Using 75 files for training.


In [20]:
for i,j in train_ds:
    print(j)

tf.Tensor([2 1 2 1 4 2 3 1 1 2 1 4 4 4 4 3 1 3 3 4 2 3 2 3 3 1 2 2 4 1 2 2], shape=(32,), dtype=int32)
tf.Tensor([2 4 1 4 3 3 1 1 2 1 3 3 2 4 1 3 2 4 3 1 2 3 4 1 4 1 3 1 4 3 2 1], shape=(32,), dtype=int32)
tf.Tensor([3 4 2 1 4 4 4 2 2 3 2], shape=(11,), dtype=int32)
